//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestGenNew200324
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// New class4.
    /// </summary>
    // *** Start programmer edit section *** (NewClass4 CustomAttributes)

    // *** End programmer edit section *** (NewClass4 CustomAttributes)
    [AutoAltered()]
    [Caption("New class4")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("NewClass4E", new string[] {
            "asd1 as \'Asd1\'"})]
    [View("NewClass4L", new string[] {
            "asd1 as \'Asd1\'"})]
    public class NewClass4 : ICSSoft.STORMNET.DataObject
    {
        
        private int fasd1;
        
        // *** Start programmer edit section *** (NewClass4 CustomMembers)

        // *** End programmer edit section *** (NewClass4 CustomMembers)

        
        /// <summary>
        /// asd1.
        /// </summary>
        // *** Start programmer edit section *** (NewClass4.asd1 CustomAttributes)

        // *** End programmer edit section *** (NewClass4.asd1 CustomAttributes)
        public virtual int asd1
        {
            get
            {
                // *** Start programmer edit section *** (NewClass4.asd1 Get start)

                // *** End programmer edit section *** (NewClass4.asd1 Get start)
                int result = this.fasd1;
                // *** Start programmer edit section *** (NewClass4.asd1 Get end)

                // *** End programmer edit section *** (NewClass4.asd1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass4.asd1 Set start)

                // *** End programmer edit section *** (NewClass4.asd1 Set start)
                this.fasd1 = value;
                // *** Start programmer edit section *** (NewClass4.asd1 Set end)

                // *** End programmer edit section *** (NewClass4.asd1 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "NewClass4E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass4E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass4E", typeof(IIS.TestGenNew200324.NewClass4));
                }
            }
            
            /// <summary>
            /// "NewClass4L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass4L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass4L", typeof(IIS.TestGenNew200324.NewClass4));
                }
            }
        }
    }
}
