//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestGenNew200324
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// New class6.
    /// </summary>
    // *** Start programmer edit section *** (NewClass6 CustomAttributes)

    // *** End programmer edit section *** (NewClass6 CustomAttributes)
    [AutoAltered()]
    [Caption("New class6")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("NewClass6E", new string[] {
            "asd2 as \'Asd2\'",
            "NewClass4 as \'New class4\'",
            "NewClass4.asd1 as \'Asd1\'"}, Hidden=new string[] {
            "NewClass4.asd1"})]
    [AssociatedDetailViewAttribute("NewClass6E", "NewClass5", "NewClass5E", true, "", "New class5", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("NewClass6E", "NewClass4", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "asd1")]
    [View("NewClass6L", new string[] {
            "asd2 as \'Asd2\'",
            "NewClass4.asd1 as \'Asd1\'"})]
    public class NewClass6 : ICSSoft.STORMNET.DataObject
    {
        
        private bool fasd2;
        
        private IIS.TestGenNew200324.NewClass4 fNewClass4;
        
        private IIS.TestGenNew200324.DetailArrayOfNewClass5 fNewClass5;
        
        // *** Start programmer edit section *** (NewClass6 CustomMembers)

        // *** End programmer edit section *** (NewClass6 CustomMembers)

        
        /// <summary>
        /// asd2.
        /// </summary>
        // *** Start programmer edit section *** (NewClass6.asd2 CustomAttributes)

        // *** End programmer edit section *** (NewClass6.asd2 CustomAttributes)
        public virtual bool asd2
        {
            get
            {
                // *** Start programmer edit section *** (NewClass6.asd2 Get start)

                // *** End programmer edit section *** (NewClass6.asd2 Get start)
                bool result = this.fasd2;
                // *** Start programmer edit section *** (NewClass6.asd2 Get end)

                // *** End programmer edit section *** (NewClass6.asd2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass6.asd2 Set start)

                // *** End programmer edit section *** (NewClass6.asd2 Set start)
                this.fasd2 = value;
                // *** Start programmer edit section *** (NewClass6.asd2 Set end)

                // *** End programmer edit section *** (NewClass6.asd2 Set end)
            }
        }
        
        /// <summary>
        /// New class6.
        /// </summary>
        // *** Start programmer edit section *** (NewClass6.NewClass4 CustomAttributes)

        // *** End programmer edit section *** (NewClass6.NewClass4 CustomAttributes)
        [PropertyStorage(new string[] {
                "NewClass4"})]
        [NotNull()]
        public virtual IIS.TestGenNew200324.NewClass4 NewClass4
        {
            get
            {
                // *** Start programmer edit section *** (NewClass6.NewClass4 Get start)

                // *** End programmer edit section *** (NewClass6.NewClass4 Get start)
                IIS.TestGenNew200324.NewClass4 result = this.fNewClass4;
                // *** Start programmer edit section *** (NewClass6.NewClass4 Get end)

                // *** End programmer edit section *** (NewClass6.NewClass4 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass6.NewClass4 Set start)

                // *** End programmer edit section *** (NewClass6.NewClass4 Set start)
                this.fNewClass4 = value;
                // *** Start programmer edit section *** (NewClass6.NewClass4 Set end)

                // *** End programmer edit section *** (NewClass6.NewClass4 Set end)
            }
        }
        
        /// <summary>
        /// New class6.
        /// </summary>
        // *** Start programmer edit section *** (NewClass6.NewClass5 CustomAttributes)

        // *** End programmer edit section *** (NewClass6.NewClass5 CustomAttributes)
        public virtual IIS.TestGenNew200324.DetailArrayOfNewClass5 NewClass5
        {
            get
            {
                // *** Start programmer edit section *** (NewClass6.NewClass5 Get start)

                // *** End programmer edit section *** (NewClass6.NewClass5 Get start)
                if ((this.fNewClass5 == null))
                {
                    this.fNewClass5 = new IIS.TestGenNew200324.DetailArrayOfNewClass5(this);
                }
                IIS.TestGenNew200324.DetailArrayOfNewClass5 result = this.fNewClass5;
                // *** Start programmer edit section *** (NewClass6.NewClass5 Get end)

                // *** End programmer edit section *** (NewClass6.NewClass5 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass6.NewClass5 Set start)

                // *** End programmer edit section *** (NewClass6.NewClass5 Set start)
                this.fNewClass5 = value;
                // *** Start programmer edit section *** (NewClass6.NewClass5 Set end)

                // *** End programmer edit section *** (NewClass6.NewClass5 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "NewClass6E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass6E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass6E", typeof(IIS.TestGenNew200324.NewClass6));
                }
            }
            
            /// <summary>
            /// "NewClass6L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass6L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass6L", typeof(IIS.TestGenNew200324.NewClass6));
                }
            }
        }
    }
}
