//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TestGenNew200324
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// New class5.
    /// </summary>
    // *** Start programmer edit section *** (NewClass5 CustomAttributes)

    // *** End programmer edit section *** (NewClass5 CustomAttributes)
    [AutoAltered()]
    [Caption("New class5")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("NewClass5E", new string[] {
            "asd3 as \'Asd3\'"})]
    public class NewClass5 : ICSSoft.STORMNET.DataObject
    {
        
        private string fasd3;
        
        private IIS.TestGenNew200324.NewClass6 fNewClass6;
        
        // *** Start programmer edit section *** (NewClass5 CustomMembers)

        // *** End programmer edit section *** (NewClass5 CustomMembers)

        
        /// <summary>
        /// asd3.
        /// </summary>
        // *** Start programmer edit section *** (NewClass5.asd3 CustomAttributes)

        // *** End programmer edit section *** (NewClass5.asd3 CustomAttributes)
        [StrLen(255)]
        public virtual string asd3
        {
            get
            {
                // *** Start programmer edit section *** (NewClass5.asd3 Get start)

                // *** End programmer edit section *** (NewClass5.asd3 Get start)
                string result = this.fasd3;
                // *** Start programmer edit section *** (NewClass5.asd3 Get end)

                // *** End programmer edit section *** (NewClass5.asd3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass5.asd3 Set start)

                // *** End programmer edit section *** (NewClass5.asd3 Set start)
                this.fasd3 = value;
                // *** Start programmer edit section *** (NewClass5.asd3 Set end)

                // *** End programmer edit section *** (NewClass5.asd3 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.TestGenNew200324.NewClass6.
        /// </summary>
        // *** Start programmer edit section *** (NewClass5.NewClass6 CustomAttributes)

        // *** End programmer edit section *** (NewClass5.NewClass6 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "NewClass6"})]
        public virtual IIS.TestGenNew200324.NewClass6 NewClass6
        {
            get
            {
                // *** Start programmer edit section *** (NewClass5.NewClass6 Get start)

                // *** End programmer edit section *** (NewClass5.NewClass6 Get start)
                IIS.TestGenNew200324.NewClass6 result = this.fNewClass6;
                // *** Start programmer edit section *** (NewClass5.NewClass6 Get end)

                // *** End programmer edit section *** (NewClass5.NewClass6 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass5.NewClass6 Set start)

                // *** End programmer edit section *** (NewClass5.NewClass6 Set start)
                this.fNewClass6 = value;
                // *** Start programmer edit section *** (NewClass5.NewClass6 Set end)

                // *** End programmer edit section *** (NewClass5.NewClass6 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "NewClass5E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass5E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass5E", typeof(IIS.TestGenNew200324.NewClass5));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of NewClass5.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfNewClass5 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfNewClass5 CustomAttributes)
    public class DetailArrayOfNewClass5 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.TestGenNew200324.DetailArrayOfNewClass5 members)

        // *** End programmer edit section *** (IIS.TestGenNew200324.DetailArrayOfNewClass5 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type NewClass5 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type NewClass5.
        /// </summary>
        public DetailArrayOfNewClass5(IIS.TestGenNew200324.NewClass6 fNewClass6) : 
                base(typeof(NewClass5), ((ICSSoft.STORMNET.DataObject)(fNewClass6)))
        {
        }
        
        public IIS.TestGenNew200324.NewClass5 this[int index]
        {
            get
            {
                return ((IIS.TestGenNew200324.NewClass5)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.TestGenNew200324.NewClass5 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
